### ISSUE TITLE
random error

### ISSUE THREAD

**Issue by Ayylmao42000** [rs-peer/rsp3#43]
Sometimes, not always, i get this error when i right click on players ?

Exception in thread "Thread-4" java.lang.AbstractMethodError: Method client.getPlayerIndices()[I is abstract
        at client.getPlayerIndices(Unknown Source)
        at org.rspeer.game.scene.Players.getLoaded(Players.java:29)
        at org.rspeer.game.query.Query.results(Query.java:21)
        at org.rspeer.game.action.tree.PlayerAction.getSource(PlayerAction.java:40)
        at org.rspeer.game.action.tree.PlayerAction.toString(PlayerAction.java:23)
        at java.lang.String.valueOf(Unknown Source)
        at java.io.PrintStream.println(Unknown Source)
        at org.rspeer.game.provider.callback.EventMediator.notifyProcessAction(EventMediator.java:100)
        at ao.hd(Unknown Source)
        at s.hx(s.java:8034)
        at client.hr(Unknown Source)
        at client.ft(Unknown Source)
        at client.ab(Unknown Source)
        at bn.e(Unknown Source)
        at bn.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Lezor91** [comment]
use modscript from dev branch
